"""Speaker notes for meeting_20260930_v4.pptx (2026-10-01), built from the presenter's own edited speaker_notes.txt.

The presenter's text for the existing slides is kept as written (speaker_notes.txt keeps every personal mark, e.g.
pronunciation hints). The notes embedded in the .pptx, which is sent to the advisor, drop those marks. New slides
(why it matters, definitions, train / val / test) get new notes. Old txt is kept as speaker_notes_v3.txt.

python docs/meeting_20260930/make_notes_v4.py  -> speaker_notes.py (NOTES, clean) + notes_user_v4.json (presenter version)
"""
import json
import re
from pathlib import Path

H = Path(__file__).resolve().parent
src = H / "speaker_notes_v3.txt"
if not src.is_file():
    src.write_text((H / "speaker_notes.txt").read_text(encoding="utf-8-sig"), encoding="utf-8")
txt = src.read_text(encoding="utf-8-sig")
old = {int(m.group(1)): m.group(2).strip() for m in re.finditer(r"【第 (\d+) 頁】[^\n]*\n(.*?)(?=【第 \d+ 頁】|\Z)", txt, re.S)}
old[18] = old[18].split("\n")[0].strip()

NEW = {
    "agenda": "接下來依序講：為什麼這個問題重要、real／filter／fake 三類的定義、我們的方法、結果（先補上 train、val、test 的成績），"
              "解釋性，最後是目前狀態和接下來兩週要做的事。",
    "why": "先講為什麼這個問題重要。偵測器會用在內容審核、遠端身分驗證、事實查核這些地方，判錯是有代價的。"
           "第一種代價是冤枉人，把美顏過的真人判成 fake：在 FF++ 上，如果要把美顏 deepfake 的漏抓壓在 5% 以內，"
           "13 個已發表的偵測器每一個都會把至少 14.5% 美顏過的真人判成 fake；換成沒看過的商用修圖，重度磨皮的真人照片"
           "有 36% 到 63% 被判成 fake。第二種代價是被利用：同一批 deepfake 加上美顏，扣掉重新壓縮的影響後，"
           "SBI 多漏抓 21.8 個百分點，2025 年的兩個 CLIP 方法也多漏 11 到 15。而修圖本身非常普遍，"
           "Bharati 等人在 TIFS 2016 就指出，修圖在社群媒體、照片分享網站，甚至證件照上都很常見。"
           "這兩種錯都來自只有 real 和 fake 兩個答案，調門檻只能在兩種錯之間交換，所以我們加第三類。",
    "defs": "那 filter 和 fake 到底怎麼分？我們的原則是看「改了什麼」，不看用什麼工具改。"
            "real 是相機拍下來的原樣，包括相機本身的處理和壓縮。filter 是畫面上還是拍攝當下的那個人，表情、姿勢、說的話都沒變，"
            "只有這張臉的外觀被改了，例如膚色、皮膚紋理、五官的平滑變形，也就是磨皮、美白、大眼、瘦臉、調色。"
            "fake 是畫面呈現的人或動作不是拍到的那個：換臉、用別人的表演驅動這張臉的 reenactment、整張合成，"
            "或是某個部位換成別人的或生成的內容。只要含有 fake 的成分就算 fake，所以美顏過的 deepfake 還是 fake。"
            "右邊的表列出容易混淆的情況：化妝算 real；用神經網路做的美顏還是 filter；reenactment 雖然身分沒變，"
            "但動作不是拍到的，所以是 fake。最後一欄是我們的資料有沒有涵蓋，表情編輯和全合成臉我們沒有測，就標 not tested。",
    "splits": "上次教授問到 training 和 testing 的成績，這頁補上。左邊是每個資料來源在 train、val、test 各有幾張，"
              "右邊是兩個模型在三個 split 上的準確率。train 的準確率是從訓練資料每列隨機抽 2,000 張量的，val 和 test 是全部。"
              "FF++ 的 macro-F1，主模型從 train 91.8、val 87.2 到 test 82.4，掉最多的是 real，從 94% 掉到 78%。"
              "fake、filter 和部位偽造在 train 跟 test 之間差不到 3 個百分點。紅色這格是這次新發現的：商用修圖沒修過的原圖，"
              "主模型連訓練時看過的原圖也只有 59.5% 判成 real，跟 val 的 55.5、test 的 57.9 差不多。"
              "所以原圖被判成 filter 這個問題在訓練資料上就存在，不是泛化失敗，這是接下來要查的重點。",
    "curves": "這頁是訓練過程。左邊是 training loss，兩個模型都穩定下降；中間是 FF++ validation 的 macro-F1，"
              "右邊是商用修圖 validation 的 filter F1。星號是選中的 checkpoint：取這兩個 validation 分數平均最高的 epoch，"
              "主模型是第 4 個（總共 8 個），小模型是第 12 個。test 資料完全沒有參與選擇。"
              "主模型的 validation macro-F1 在第 4 個 epoch 之後就持平了，training loss 還在下降。",
    "confusion": "這是 FF++ 在 train、val、test 三個 split 的 confusion matrix，每一列是真實類別，加起來是 100%，"
                 "上排是主模型，下排是小模型。fake 和 filter 在三個 split 都很穩定，主模型的差距在 2.1 個百分點以內；"
                 "主要的落差在 real 那一列：主模型的 real 在 train 是 94%，到 test 剩 78%，流失的部分 13% 跑到 filter、9% 跑到 fake。"
                 "所以接下來要查的是真臉為什麼會往 filter 偏，FF++ 和商用修圖的原圖是同一個問題。",
}

# old slide k -> new position; "agenda" etc. are new texts
ORDER = [1, 2, "agenda", "why", 4, "defs", 5, 6, 7, 8, 9, "splits", "curves", "confusion", 10, 11, 12, 13, 14, 15, 16, 17, 18]
user = []
for k in ORDER:
    t = NEW[k] if isinstance(k, str) else old[k]
    if k == 4:
        t = t.replace("所以我們加第三個類別 filter：身分沒變、只是被修過圖。", "所以我們加第三個類別 filter，下一頁講它的定義。")
    if k == 17:
        t = t.replace("以及可以在手機跑的小模型。", "以及可以在手機跑的小模型，也補上了三類的定義和 train、val、test 的成績。")
        t = t.replace("會查清楚為什麼 44% 沒修過的原圖會被判成 filter；", "會查清楚為什麼 40% 到 44% 沒修過的原圖會被判成 filter，連訓練用的原圖也是；")
    user.append(t)


def clean(t):
    t = t.replace("連兩個CLIP方法 欸 fer、 fo-ren-sics a-dap-ter  和 也多了 11 和 15", "連兩個 CLIP 方法 Effort 和 Forensics Adapter 也多了 11 和 15")
    t = re.sub(r"\((厄|ㄟ[^)]*)\)", "", t)
    t = t.replace("更強的 reason  模糊的 更清楚的", "")
    return re.sub(r"[ \t]{2,}", " ", t).strip()


notes = [clean(t) for t in user]
assert len(notes) == 23
(H / "notes_user_v4.json").write_text(json.dumps(user, ensure_ascii=False, indent=1), encoding="utf-8")
body = ",\n".join("    " + json.dumps(n, ensure_ascii=False) for n in notes)
(H / "speaker_notes.py").write_text(
    '"""Speaker notes (Traditional Chinese, Taiwan) for meeting_20260930_v4.pptx, one entry per slide in order.\n'
    'Generated by make_notes_v4.py from the presenter\'s edited speaker_notes.txt; imported by build_deck.py."""\n'
    "NOTES = [\n" + body + ",\n]\n", encoding="utf-8")
for i, n in enumerate(notes, 1):
    print(i, n[:60])
